# These are supported funding model platforms

github: [hirenpattani]
patreon: hirenpattani
tidelift: pypi/flask
custom: ["https://www.paypal.me/kashyappandya7", "https://www.paypal.me/dhartidalsania"]
